### ISSUE TITLE
Auto-import ~/.cargo as project

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/corrosion#172]
In many cases, it's useful for the end-user to have ~/.cargo available as project in the workspace, to set breakpoints, to get code assist, to do some searches...
Corrosion should automatically import ~/.cargo in the workspace.
In a first iteration, we can making happen automatically without question nor option. Then, if some complain with good reasons, we can have a preference to control what to do when .cargo is missing (auto-import, ignore, prompt user).

**Comment by norru** [comment]
If you push to snapshot I'll give this a spin.

What triggers it? Creatiing a new project?

**Comment by mickaelistria** [comment]
> If you push to snapshot I'll give this a spin.

We're currently facing issues with build https://bugs.eclipse.org/bugs/show_bug.cgi?id=541426

> What triggers it? Creatiing a new project?

Currently, more or less startup of the IDE (startup of the Corrosion bundle to be precise).
So people who update would get this imported even if they don't go through wizards. But I'm not against adding other entry-points if you think it's necessary. I'm just not sure we do need any other entry points than this one for good results.

**Comment by norru** [comment]
No worries, not in a rush.

**Comment by norru** [comment]
Hi @mickaelistria, Eclipse told me there was a new Corrosion this morning. I've upgraded but the .cargo autoimport is not there. I don't know if the last Corrosion drop contains this fix.

**Comment by norru** [comment]
Manually adding `.cargo` as a project is a great workaround though :+1:

**Comment by mickaelistria** [comment]
It doesn't contain it yet.

**Comment by norru** [comment]
@mickaelistria About this: is it still required? Didn't you change something in LSP that "binds" editors to filesystem items rather than Resources?

**Comment by mickaelistria** [comment]
I don't know whether it's still required. As I'm not really a user of Corrosion, I don't feel able to judge that.
You can try the following:
1. Close all files
2. Delete the `.cargo` project (if it's not showing up, you can get to the Project Configuration menu (arrow down in the view toolbar) > Filters and customization > Filters > uncheck `.* resources`)
3. Open a Rust file and navigate to external files

From here, you should have LS enabled for those external files; and you'll see whether it's better than having the `.cargo` folder. If you try it and report it's better without the `.cargo` folder, then we can remove the code that automatically adds it.

**Comment by norru** [comment]
Just tried this: removing the `.cargo` project causes RLS to fail all library lookups. Never mind.

**Comment by mickaelistria** [comment]
I think that the fact that it takes several seconds is an RLS issue. Can you please check the language server log and compare the timestamp of the "definition" request with timestamp of the answer (the `id` field is used to match response with request) to verify it's really the LS taking time and not another issue?

**Comment by norru** [comment]
> I think that the fact that it takes several seconds is an RLS issue

Most certainly is. Is there anything that we can do to handle this better?

**Comment by mickaelistria** [comment]
I don't think there is something easy to implement. The link resolution in Eclipse IDE is unfortunately synchronous blocking in the UI Thread, so we can't easily deal with long running operations... 
Other LSs work fine, I'd rather see the workforce spent on improving RLS than building a complex solution/workaround for that undesired case in the Eclipse stack.

**Comment by norru** [comment]
![Selection_164](https://user-images.githubusercontent.com/889291/55315820-9e3c7f00-545c-11e9-8259-683d87cea34a.png)

**Comment by norru** [comment]
Looks like *all* the `textDocument/definition` are failing with timeout after a very short time (~1sec), but only in the .cargo entries. The other source files are fine. Looks like LSP is timing out almost immediately rather than waiting for a reply.

> Other LSs work fine, I'd rather see the workforce spent on improving RLS than building a complex solution/workaround for that undesired case in the Eclipse stack.

```
[t=1554109375282] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"78","method":"textDocument/definition","params":{"textDocument":{"uri":"file:///home/norru/.cargo/registry/src/github.com-1ecc6299db9ec823/zip-0.5.1/src/compression.rs"},"position":{"line":6,"character":12}}}
```

```
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.eclipse.lsp4e.operations.declaration.OpenDeclarationHyperlinkDetector.detectHyperlinks(OpenDeclarationHyperlinkDetector.java:79)
	at org.eclipse.ui.texteditor.HyperlinkDetectorRegistry$HyperlinkDetectorDelegate.detectHyperlinks(HyperlinkDetectorRegistry.java:81)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:289)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:262)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:457)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:216)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5783)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1411)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4579)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
```

**Comment by norru** [comment]
I have opened an RLS ticket.

I can guess that the first thing they'll want to know is "What happens if you make your timeout longer?"

How do we do such? Is it hardcoded? If it is, it's something that we need to expose as an option.

**Comment by mickaelistria** [comment]
The pop-up you see can be related and could be a bug in LSP4E (because of some unspecified behavior for this case in LSP spec). Because of the error you see in pop-up, RLS may simply not answer at all, which isn't very nice ;)
In LSP4E, the default path when opening some random file (like a file in .cargo) is `/`. I don't know whether it's what's best and LSP spec doesn't suggest anything else. Other LSs like VSCode or TypeScript ones accept it without trouble. RLS doesn't.

> I can guess that the first thing they'll want to know is "What happens if you make your timeout longer?" How do we do such? Is it hardcoded?

Even if the clients sends a timeout, the request was still sent and the future is still expected. The sequence would be request, then client-side timeout, then server response received, but is ignored on client-side.
So if you see nothing in the message log, it's most likely that RLS sends nothing.
