### ISSUE TITLE
"Rename" refactoring is very unreliable

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#187]
EDIT: the "first time" is a red herring. "Rename" is generally flaky.

[rename_error_stack_trace.txt](https://github.com/eclipse/corrosion/files/2680991/rename_error_stack_trace.txt)
The first time I attempt to rename a local symbol it works fine. If I try then to change another local symbol, I get errors of various sorts:

- "no information for symbol"/"nothing to rename"
```
LSP4E to org.eclipse.corrosion.rls:{"jsonrpc":"2.0","id":"4047","method":"textDocument/rename","params":{"textDocument":{"uri":"file://<snip>.rs"},"position":{"line":993,"character":9},"newName":"view_data"}}
org.eclipse.corrosion.rls to LSP4E:
[...]
org.eclipse.corrosion.rls to LSP4E:{"jsonrpc":"2.0","method":"window/progress","params":{"done":true,"id":"progress_5532","title":"Indexing"}}
org.eclipse.corrosion.rls to LSP4E:{"jsonrpc":"2.0","method":"window/showMessage","params":{"message":"Rename failed: no information for symbol","type":2}}
```

Clue: the position reported in the log doesn't match the position of the symbol (off by one line)

- Internal error
```
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4583)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation$1.run(RefactoringWizardOpenOperation.java:192)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:212)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:126)
	at org.eclipse.lsp4e.operations.rename.LSPRenameHandler.execute(LSPRenameHandler.java:66)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:207)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:436)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4583)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
Caused by: org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
	at org.eclipse.ltk.core.refactoring.RefactoringStatusEntry.<init>(RefactoringStatusEntry.java:119)
	at org.eclipse.ltk.core.refactoring.RefactoringStatusEntry.<init>(RefactoringStatusEntry.java:87)
	at org.eclipse.ltk.core.refactoring.RefactoringStatus.addFatalError(RefactoringStatus.java:557)
	at org.eclipse.ltk.core.refactoring.RefactoringStatus.addFatalError(RefactoringStatus.java:544)
	at org.eclipse.lsp4e.operations.rename.LSPRenameProcessor.handleError(LSPRenameProcessor.java:118)
	at org.eclipse.lsp4e.operations.rename.LSPRenameProcessor.checkFinalConditions(LSPRenameProcessor.java:106)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.checkFinalConditions(ProcessorBasedRefactoring.java:225)
	at org.eclipse.ltk.core.refactoring.CheckConditionsOperation.run(CheckConditionsOperation.java:86)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:122)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:210)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2319)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Root exception:
org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
	at org.eclipse.ltk.core.refactoring.RefactoringStatusEntry.<init>(RefactoringStatusEntry.java:119)
	at org.eclipse.ltk.core.refactoring.RefactoringStatusEntry.<init>(RefactoringStatusEntry.java:87)
	at org.eclipse.ltk.core.refactoring.RefactoringStatus.addFatalError(RefactoringStatus.java:557)
	at org.eclipse.ltk.core.refactoring.RefactoringStatus.addFatalError(RefactoringStatus.java:544)
	at org.eclipse.lsp4e.operations.rename.LSPRenameProcessor.handleError(LSPRenameProcessor.java:118)
	at org.eclipse.lsp4e.operations.rename.LSPRenameProcessor.checkFinalConditions(LSPRenameProcessor.java:106)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.checkFinalConditions(ProcessorBasedRefactoring.java:225)
	at org.eclipse.ltk.core.refactoring.CheckConditionsOperation.run(CheckConditionsOperation.java:86)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:122)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:210)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2319)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by mickaelistria** [comment]
Would you blame LSP4E or RLS? Since rename worked once, I tend to believe LSP4E seems fine and it's RLS sending wrong position. What do you think?

**Comment by norru** [comment]
Also NPE needs to be looked at anyway.

**Comment by mickaelistria** [comment]
> Not sure. Isn't the wrong position in the request too? Is it not LSP4E creating that message?

LSP4E creates the request. I can't tell whether it's correct, it depends on your file and your action.

> Also NPE needs to be looked at anyway.

Right, can you please open a bug for that to LSP4E?

**Comment by norru** [comment]
> LSP4E creates the request. I can't tell whether it's correct, it depends on your file and your action.

I tried to rename a symbol on line 994. The request sent to RLS by LSP4E was referencing line 993.

**Comment by norru** [comment]
There is one already

https://bugs.eclipse.org/bugs/show_bug.cgi?id=320986

**Comment by mickaelistria** [comment]
It's not the same bug. Bug 320986 is about JDT (Java) rename. While they can have a part in common, the LSP/Corrosion rename and JDT one are different stories.

**Comment by norru** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=542814

**Comment by mickaelistria** [comment]
> The first time I attempt to rename a local symbol it works fine. If I try then to change another local symbol, I get errors of various sorts:

That's quite strange it works once and then fails.
Can you please try to reproduce it with a mimimal .rs file and share the logs?

**Comment by norru** [comment]
Rename is still broken on all files, no matter the minimal .rs file. Here's some log:

LSP4E to org.eclipse.corrosion.rls:Content-Length: 216


```
LSP4E to org.eclipse.corrosion.rls:{"jsonrpc":"2.0","id":"17303","method":"textDocument/rename","params":{"textDocument":{"uri":"..."},"position":{"line":354,"character":7},"newName":"scale"}}
org.eclipse.corrosion.rls to LSP4E:{"jsonrpc":"2.0","id":"17303","result":{"changes":{"...":[{"range":{"start":{"line":354,"character":6},"end":{"line":354,"character":13}},"newText":"scale"},{"range":{"start":{"line":358,"character":69},"end":{"line":358,"character":76}},"newText":"scale"},{"range":{"start":{"line":359,"character":69},"end":{"line":359,"character":76}},"newText":"scale"},{"range":{"start":{"line":360,"character":84},"end":{"line":360,"character":91}},"newText":"scale"},{"range":{"start":{"line":361,"character":76},"end":{"line":361,"character":83}},"newText":"scale"},{"range":{"start":{"line":363,"character":94},"end":{"line":363,"character":101}},"newText":"scale"},{"range":{"start":{"line":364,"character":106},"end":{"line":364,"character":113}},"newText":"scale"},{"range":{"start":{"line":367,"character":81},"end":{"line":367,"character":88}},"newText":"scale"},{"range":{"start":{"line":369,"character":90},"end":{"line":369,"character":97}},"newText":"scale"},{"range":{"start":{"line":370,"character":84},"end":{"line":370,"character":91}},"newText":"scale"},{"range":{"start":{"line":371,"character":84},"end":{"line":371,"character":91}},"newText":"scale"},{"range":{"start":{"line":372,"character":84},"end":{"line":372,"character":91}},"newText":"scale"},{"range":{"start":{"line":376,"character":84},"end":{"line":376,"character":91}},"newText":"scale"},{"range":{"start":{"line":377,"character":74},"end":{"line":377,"character":81}},"newText":"scale"},{"range":{"start":{"line":378,"character":71},"end":{"line":378,"character":78}},"newText":"scale"},{"range":{"start":{"line":383,"character":75},"end":{"line":383,"character":82}},"newText":"scale"}]}}}
```

**Comment by norru** [comment]
Changed title as the problem doesn't appear to be related to the number of successes before the failure.

**Comment by norru** [comment]
https://github.com/rust-lang/rls/issues/1322

**Comment by norru** [comment]
Another NPE while trying to rename a local variable

```
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:401)
	at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog2.run(RefactoringWizardDialog2.java:324)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizard.internalPerformFinish(RefactoringWizard.java:639)
	at org.eclipse.ltk.ui.refactoring.UserInputWizardPage.performFinish(UserInputWizardPage.java:148)
	at org.eclipse.lsp4e.operations.rename.LSPRenameRefactoringWizard$RenameInputWizardPage.performFinish(LSPRenameRefactoringWizard.java:98)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizard.performFinish(RefactoringWizard.java:713)
	at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog2.okPressed(RefactoringWizardDialog2.java:450)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:469)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5663)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1386)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4472)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:822)
	at org.eclipse.jface.window.Window.open(Window.java:798)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation$1.run(RefactoringWizardOpenOperation.java:192)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:212)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:126)
	at org.eclipse.lsp4e.operations.rename.LSPRenameHandler.lambda$1(LSPRenameHandler.java:73)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:669)
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:1997)
	at org.eclipse.lsp4e.operations.rename.LSPRenameHandler.execute(LSPRenameHandler.java:61)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5663)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1386)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4472)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4e.refactoring.LSPTextChange.getModifiedElement(LSPTextChange.java:134)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.addToTextChangeMap(ProcessorBasedRefactoring.java:432)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.addToTextChangeMap(ProcessorBasedRefactoring.java:446)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.createChange(ProcessorBasedRefactoring.java:296)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:125)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:210)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Root exception:
java.lang.NullPointerException
	at org.eclipse.lsp4e.refactoring.LSPTextChange.getModifiedElement(LSPTextChange.java:134)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.addToTextChangeMap(ProcessorBasedRefactoring.java:432)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.addToTextChangeMap(ProcessorBasedRefactoring.java:446)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.createChange(ProcessorBasedRefactoring.java:296)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:125)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:210)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by mickaelistria** [comment]
Can you please report this stack to LSP4E ?

**Comment by norru** [comment]
Done https://bugs.eclipse.org/bugs/show_bug.cgi?id=544985

That said, reporting a bug via the Eclipse tracker is not enjoyable. The bug reporting system in Eclipse is dated and unfriendly.

Also difficult to link from/to GitHub related projects and repositories.

Is there a chance that LSP4E will be fully migrated to GitHub in the foreseeable future?

**Comment by mickaelistria** [comment]
>
> Also difficult to link from/to GitHub related projects and repositories.
>
So far, URL links always worked ;)

Is there a chance that LSP4E will be fully migrated to GitHub in the
> foreseeable future?
>
Please bring this question to lsp4e-dev@eclipse.org.

**Comment by norru** [comment]
"Rename" refactor has no effect. Selecting and identifier and invoking the command produces no results, not even in the LSP log.

Current snapshot of LSP4E and corrosion as 08/03/2019.

**Comment by mickaelistria** [comment]
Ok. Can you please elaborate with some minimal steps to reproduce the issue (maybe sharing an example project)? It seems like there is a very probable case I missed in LSP4E.
FWIW, we're kind of in a rush if we want it fix for 2019-03, only one week left before everything gets frozen. I'll work on it with high priority, but need your help here to make sure I'll try to fix the right thing ;)

**Comment by mickaelistria** [comment]
How are things with LSP4E 0.9.0 release?

**Comment by mickaelistria** [comment]
I just tried and it seems to work. Please reopen if it fails for you.

**Comment by norru** [comment]
Local variables seem to work now, will test the rest soon :)

**Comment by norru** [comment]
Just got this while renaming a constant.
<details>
```
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:399)
	at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog2.run(RefactoringWizardDialog2.java:324)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizard.internalPerformFinish(RefactoringWizard.java:639)
	at org.eclipse.ltk.ui.refactoring.UserInputWizardPage.performFinish(UserInputWizardPage.java:148)
	at org.eclipse.lsp4e.operations.rename.LSPRenameRefactoringWizard$RenameInputWizardPage.performFinish(LSPRenameRefactoringWizard.java:98)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizard.performFinish(RefactoringWizard.java:713)
	at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog2.okPressed(RefactoringWizardDialog2.java:450)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:469)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5783)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1411)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4579)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation$1.run(RefactoringWizardOpenOperation.java:192)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:212)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:126)
	at org.eclipse.lsp4e.operations.rename.LSPRenameHandler.lambda$2(LSPRenameHandler.java:76)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4582)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
Caused by: org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
	at org.eclipse.ltk.core.refactoring.RefactoringStatusEntry.<init>(RefactoringStatusEntry.java:119)
	at org.eclipse.ltk.core.refactoring.RefactoringStatusEntry.<init>(RefactoringStatusEntry.java:87)
	at org.eclipse.ltk.core.refactoring.RefactoringStatus.addFatalError(RefactoringStatus.java:557)
	at org.eclipse.ltk.core.refactoring.RefactoringStatus.addFatalError(RefactoringStatus.java:544)
	at org.eclipse.lsp4e.operations.rename.LSPRenameProcessor.handleError(LSPRenameProcessor.java:120)
	at org.eclipse.lsp4e.operations.rename.LSPRenameProcessor.checkFinalConditions(LSPRenameProcessor.java:108)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.checkFinalConditions(ProcessorBasedRefactoring.java:225)
	at org.eclipse.ltk.core.refactoring.CheckConditionsOperation.run(CheckConditionsOperation.java:86)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:122)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:210)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Root exception:
org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
	at org.eclipse.ltk.core.refactoring.RefactoringStatusEntry.<init>(RefactoringStatusEntry.java:119)
	at org.eclipse.ltk.core.refactoring.RefactoringStatusEntry.<init>(RefactoringStatusEntry.java:87)
	at org.eclipse.ltk.core.refactoring.RefactoringStatus.addFatalError(RefactoringStatus.java:557)
	at org.eclipse.ltk.core.refactoring.RefactoringStatus.addFatalError(RefactoringStatus.java:544)
	at org.eclipse.lsp4e.operations.rename.LSPRenameProcessor.handleError(LSPRenameProcessor.java:120)
	at org.eclipse.lsp4e.operations.rename.LSPRenameProcessor.checkFinalConditions(LSPRenameProcessor.java:108)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.checkFinalConditions(ProcessorBasedRefactoring.java:225)
	at org.eclipse.ltk.core.refactoring.CheckConditionsOperation.run(CheckConditionsOperation.java:86)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:122)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:210)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```
</details>

**Comment by norru** [comment]
Rename seems to have become more stable in general. Will open new bugs for specific cases.
