### ISSUE TITLE
IDE freeze on tab editor closing

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#237]
No activity, no dialog, just stuck.

The last thing I attempted was to close an editor tab containing Rust source.
[stalled_ide_no_dialog.txt](https://github.com/eclipse/corrosion/files/2989011/stalled_ide_no_dialog.txt)

Waiting doesn't fix it. Had to forcibly close Eclipse.

**Comment by mickaelistria** [comment]
Thank you. The interesting subpart is

```
"main" #1 prio=6 os_prio=0 tid=0x0000000002293000 nid=0x358b waiting for monitor entry [0x00007fff88c2c000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:66)
	- waiting to lock <0x00000004265e8588> (a java.lang.Object)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$1(LanguageServerWrapper.java:213)
	at org.eclipse.lsp4e.LanguageServerWrapper$$Lambda$453/487780337.consume(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:91)
	at com.sun.proxy.$Proxy26.shutdown(Unknown Source)
	at org.eclipse.lsp4e.LanguageServerWrapper.stop(LanguageServerWrapper.java:351)
	- locked <0x00000004265c6160> (a org.eclipse.lsp4e.LanguageServerWrapper)
	at org.eclipse.lsp4e.LanguageServerWrapper.disconnect(LanguageServerWrapper.java:511)
	at org.eclipse.lsp4e.LanguageServerWrapper$1.bufferDisposed(LanguageServerWrapper.java:123)
	at org.eclipse.core.internal.filebuffers.TextFileBufferManager$12.run(TextFileBufferManager.java:789)
```

The `stop` operation should be less blocking.

**Comment by mickaelistria** [comment]
It's an occurrence of https://bugs.eclipse.org/bugs/show_bug.cgi?id=545023

**Comment by mickaelistria** [comment]
Closed as it is fixed upstream. Please reopen if you still face the issue with latest release.
