### ISSUE TITLE
NPE on a new project, if RLS is not detected in the system

### ISSUE THREAD

**Issue by snuk182** [eclipse/corrosion#249]
Windows 10 x64 + unstable latest Corrosion.
I didn't use RLS, and so it is not installed in the system.
Reproduction: on a new project creation a window pops up which says the preferences are invalid, and prompts to change them. On pressing the preferences an "invalid values" message pops up, and no new preferences can be applied (Apply button is always disabled).
```
!ENTRY org.eclipse.jface 4 2 2019-04-29 12:31:40.927
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at org.eclipse.corrosion.CorrosionPlugin.validateCommandVersion(CorrosionPlugin.java:121)
	at org.eclipse.corrosion.CorrosionPreferencePage.isRustupSectionValid(CorrosionPreferencePage.java:197)
	at org.eclipse.corrosion.CorrosionPreferencePage.isPageValid(CorrosionPreferencePage.java:144)
	at org.eclipse.corrosion.CorrosionPreferencePage.lambda$6(CorrosionPreferencePage.java:393)
	at org.eclipse.corrosion.ui.InputComponent.setValue(InputComponent.java:76)
	at org.eclipse.corrosion.CorrosionPreferencePage.initializeContent(CorrosionPreferencePage.java:125)
	at org.eclipse.corrosion.CorrosionPreferencePage.createContents(CorrosionPreferencePage.java:105)
	... etc
```

**Comment by snuk182** [comment]
```
!SESSION 2019-04-29 10:40:24.213 -----------------------------------------------
eclipse.buildId=4.11.0.I20190307-0500
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.egit.core 1 0 2019-04-29 10:43:07.274
!MESSAGE Using Apache MINA sshd as ssh client.

!ENTRY org.eclipse.egit.ui 2 0 2019-04-29 10:43:34.623
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\plyhuns'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.
!SESSION 2019-04-29 10:45:59.801 -----------------------------------------------
eclipse.buildId=4.11.0.I20190307-0500
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -data file:/C:/Users/plyhuns/other/workspace-corrosion/ -product org.eclipse.epp.package.java.product
```

**Comment by snuk182** [comment]
![image](https://user-images.githubusercontent.com/493209/56891909-4ce4d700-6a7e-11e9-8ed1-b17bd8ef6e98.png)
![image](https://user-images.githubusercontent.com/493209/56891927-5ec67a00-6a7e-11e9-9bd5-0cdb8fe47fd8.png)
![image](https://user-images.githubusercontent.com/493209/56891966-743ba400-6a7e-11e9-9acf-c2e6fb1ad808.png)

**Comment by norru** [comment]
Hi @snuk182, do you mind having a look at https://github.com/eclipse/corrosion/blob/master/documentation/Troubleshooting.md to see if there are some clues on how to solve this problem. If not, at least it could help to have more detailed logs?

**Comment by snuk182** [comment]
Looks like I'm not allowed to attach files here, here is a gist of it https://gist.github.com/snuk182/e6fa99b007c72311168203beb8b98c2c
I've checked the troubleshooting guide before filing a ticket, with no much use.

**Comment by norru** [comment]
"Rust Language Server not found."

**Comment by snuk182** [comment]
I have installed it after I got the initial message about its requirement.

**Comment by norru** [comment]
is `cargo\bin` directory in Eclipse's `%PATH%`?

- try open a `cmd` window
- run `rls --cli`

if it says something like "Command not found" the %PATH% is missing an entry

**Comment by snuk182** [comment]
Reinstallation of RLS from the fresh Rust release helped, Corrosion does not error.

**Comment by norru** [comment]
Hi @snuk182, nice fix! Do you mind closing this issue if you are happy? Many thanks.
