### ISSUE TITLE
Severe RLS process leak causes OS hang.

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#259]
LSP4E/lsp4j appears to be spamming RLS instances in some TBD circumstances. In one instance I got my machine into a system OOM from which I recovered with difficulty (`pid 20368 is` Eclipse's JVM).

Perhaps LSP4E is somehow "losing" the RLS and respawning it even if the process is not actually dead?

I started observing this behaviour today, after a lsp4j snapshot update.

```
norru    20497 20368  0 16:28 ?        00:00:13 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    21762 20368  2 18:26 ?        00:00:06 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    22293 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    22319 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    22911 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    22940 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23284 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23647 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23660 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23673 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23720 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23747 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23763 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23779 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23798 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23827 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23846 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23879 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    23913 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    24358 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    24387 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    24408 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    24424 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    24441 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    24455 20368  0 18:27 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    24761 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    24773 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    24804 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    24821 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    24834 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25154 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25169 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25203 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25218 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25235 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25264 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25277 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25290 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25303 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25318 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25339 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25644 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25669 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25682 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    25731 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26011 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26023 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26072 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26087 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26104 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26376 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26390 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26404 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26417 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26430 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26446 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26795 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26807 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26820 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26835 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26848 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    26863 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    27158 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    27172 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    27188 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    27201 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    27214 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    27227 20368  0 18:28 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    27533 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    27549 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    27564 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    27579 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    27596 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    27609 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    28234 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    28249 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    28261 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    28274 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    28287 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    28302 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    28617 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    28630 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    28645 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    28660 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    28673 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
norru    28689 20368  0 18:29 ?        00:00:00 /home/norru/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rls
```

At the same time, I get these Eclipse errors:

```
java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.eclipse.lsp4e.LoggingStreamConnectionProviderProxy.stop(LoggingStreamConnectionProviderProxy.java:210)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$5(LanguageServerWrapper.java:362)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$6(LanguageServerWrapper.java:369)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
	at java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:884)
	at java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2196)
	at org.eclipse.lsp4e.LanguageServerWrapper.stop(LanguageServerWrapper.java:368)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:185)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:582)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:506)
	at org.eclipse.lsp4e.operations.declaration.OpenDeclarationHyperlinkDetector.detectHyperlinks(OpenDeclarationHyperlinkDetector.java:73)
	at org.eclipse.ui.texteditor.HyperlinkDetectorRegistry$HyperlinkDetectorDelegate.detectHyperlinks(HyperlinkDetectorRegistry.java:81)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:289)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:262)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:457)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:216)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5874)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5138)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
		at java.io.OutputStream.write(OutputStream.java:116)
		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
		... 42 more

```

**Comment by norru** [comment]
Not seen in latest version of LSP4E. Reopen if necessary.
