### ISSUE TITLE
Problem markers suddenly stops updating.

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#261]
After some time of continuous editing/building, the "Problem" windows stops updating and refreshing with new errors/warnings.

RLS appears to be running and responding to requests.

Workaround is to restart the IDE periodically *or* force kill the `rls` processes spawned by Eclipse from the OS (see below).

UPDATE: killing the processes is not a viable workaround. After doing that the IDE gets stuck in a continuos "Building" loop.

**Comment by mickaelistria** [comment]
Is the view content the only issue? Ie are problem markers still properly shown and updated in the editor and project explorer when this happen?

**Comment by norru** [comment]
All the markers are "stuck" too.

**Comment by norru** [comment]
More information, just got this again:

- `pkill rls` from terminal causes the following error to appear in the Error Log

```
java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.eclipse.lsp4e.LoggingStreamConnectionProviderProxy.stop(LoggingStreamConnectionProviderProxy.java:210)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$5(LanguageServerWrapper.java:362)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$6(LanguageServerWrapper.java:369)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
	at java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:884)
	at java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2196)
	at org.eclipse.lsp4e.LanguageServerWrapper.stop(LanguageServerWrapper.java:368)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:185)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:582)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:506)
	at org.eclipse.lsp4e.operations.highlight.HighlightReconcilingStrategy.collectHighlights(HighlightReconcilingStrategy.java:197)
	at org.eclipse.lsp4e.operations.highlight.HighlightReconcilingStrategy.lambda$0(HighlightReconcilingStrategy.java:124)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
		at java.io.OutputStream.write(OutputStream.java:116)
		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
		... 14 more
```

And afterwards, the markers resume proper updating.

**Comment by mickaelistria** [comment]
Were you still seeing the `publishDiagnostics` notifications in the log when this happens? Do they seem correct (especially the uri)? If yes to both, then LSP4E is most likely the one to blame; otherwise it's RLS.

**Comment by norru** [comment]
Just found that killing the processes is not a viable workaround. After doing that the IDE gets stuck in a continuos "Building" loop.

**Comment by norru** [comment]
Yes, `publishDiagnostics` messages are being generated in the logs.

**Comment by norru** [comment]
I don't know exactly what triggers this behaviour but I think it always see it happen while I edit and save during a background build (which is, almost always).

**Comment by norru** [comment]
Additional information: this is often triggered by hitting `Ctrl+Shift+F` (formatting), which incidentally also triggers https://github.com/eclipse/corrosion/issues/243.

**Comment by akurtakov** [comment]
Now that corrosion uses rust-analyzer is this one fixed for you/

**Comment by akurtakov** [comment]
Closing due to lack of interest.
