### ISSUE TITLE
Error indications only update once

### ISSUE THREAD

**Issue by llowrey** [eclipse/corrosion#275]
After I open the first rust source file I get error indications but after that, the error indications don't change and I don't get new ones. If I kill the rls process(es) the error indications will update, but again, only once. I noticed I end up with multiple rls processes. Every time I go to a new rs file I seem to get a new rls process.

Resource|Version
--- | ---
OS|Windows 10 x64
rls|1.37.0 (124483d 2019-07-01)
eclipse|2019-06 (4.12.0) Build id: 20190614-1200
Corrosion|Rust edition in Eclipse IDE	0.4.1.201903251734

From org.eclipse.corrosion.rls.log
```
[t=1567529325453] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 60


[t=1567529325455] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"8","method":"shutdown","params":null}
[t=1567529325460] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 60


[t=1567529325461] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"9","method":"shutdown","params":null}
[t=1567529325630] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 1285


[t=1567529325632] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":15380,"rootPath":"/C:/Users/llowrey/Documents/workspaces/personal/testo/","rootUri":"file:///C:/Users/llowrey/Documents/workspaces/personal/testo/","initializationOptions":{"settings":{"rust":{"clippy_preference":"on"}}},"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"undo"},"symbol":{},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true}},"hover":{},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{"symbolKind":{"valueSet":[18,17,5,14,9,10,22,24,8,1,12,11,20,6,2,3,21,16,19,25,4,7,15,23,26,13]},"hierarchicalDocumentSymbolSupport":true},"formatting":{},"rangeFormatting":{},"definition":{},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":true},"codeLens":{},"documentLink":{},"colorProvider":{},"rename":{}}},"clientName":"Eclipse IDE","trace":"off"}}
[t=1567529325635] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 60


[t=1567529325638] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"2","method":"shutdown","params":null}
[t=1567529325661] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","id":"1","result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[".",":"]},"definitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"documentFormattingProvider":true,"documentRangeFormattingProvider":false,"renameProvider":true,"executeCommandProvider":{"commands":["rls.applySuggestion-20876","rls.deglobImports-20876"]}}}}
[t=1567529325665] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"window/progress","params":{"done":null,"id":"progress_1","message":null,"percentage":null,"title":"Building"}}
[t=1567529325727] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"window/progress","params":{"done":null,"id":"progress_1","message":"testo","percentage":null,"title":"Building"}}
[t=1567529325730] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"window/progress","params":{"done":null,"id":"progress_1","message":"testo cfg(test)","percentage":null,"title":"Building"}}
[t=1567529325840] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 1285


[t=1567529325843] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":15380,"rootPath":"/C:/Users/llowrey/Documents/workspaces/personal/testo/","rootUri":"file:///C:/Users/llowrey/Documents/workspaces/personal/testo/","initializationOptions":{"settings":{"rust":{"clippy_preference":"on"}}},"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"undo"},"symbol":{},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true}},"hover":{},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{"symbolKind":{"valueSet":[18,17,5,14,9,10,22,24,8,1,12,11,20,6,2,3,21,16,19,25,4,7,15,23,26,13]},"hierarchicalDocumentSymbolSupport":true},"formatting":{},"rangeFormatting":{},"definition":{},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":true},"codeLens":{},"documentLink":{},"colorProvider":{},"rename":{}}},"clientName":"Eclipse IDE","trace":"off"}}
[t=1567529325876] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","id":"1","result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[".",":"]},"definitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"documentFormattingProvider":true,"documentRangeFormattingProvider":false,"renameProvider":true,"executeCommandProvider":{"commands":["rls.applySuggestion-18296","rls.deglobImports-18296"]}}}}
[t=1567529325880] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 52


[t=1567529325884] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","method":"initialized","params":{}}
[t=1567529325888] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"window/progress","params":{"done":null,"id":"progress_1","message":null,"percentage":null,"title":"Building"}}
[t=1567529325888] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 214


[t=1567529325891] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"2","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///C:/Users/llowrey/Documents/workspaces/personal/testo/src/main.rs"},"position":{"line":2,"character":12}}}
[t=1567529325891] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"client/registerCapability","id":1,"params":{"registrations":[{"id":"rls-watch","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"C:\\Users\\llowrey\\Documents\\workspaces\\personal\\testo\\/Cargo.lock"},{"globPattern":"C:\\Users\\llowrey\\Documents\\workspaces\\personal\\testo\\/target","kind":4},{"globPattern":"C:\\Users\\llowrey\\Documents\\workspaces\\personal\\testo\\Cargo.toml"}]}}]}}
[t=1567529325895] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 268


[t=1567529325896] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","id":"2","result":[]}
[t=1567529325898] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///C:/Users/llowrey/Documents/workspaces/personal/testo/src/main.rs","languageId":"rs","version":1,"text":"fn main() {\n    println!(\"Hello, world!\");\n\tlet a \u003d 9x;\n}\n"}}}
[t=1567529325901] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 38


[t=1567529325904] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":1,"result":null}
[t=1567529326075] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"window/progress","params":{"done":true,"id":"progress_1","message":null,"percentage":null,"title":"Building"}}
[t=1567529326078] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"window/progress","params":{"done":null,"id":"progress_0","message":null,"percentage":null,"title":"Indexing"}}
[t=1567529326079] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"window/progress","params":{"done":null,"id":"progress_1","message":"testo","percentage":null,"title":"Building"}}
[t=1567529326081] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"unused_variables","message":"unused variable: `a`\n\nnote: #[warn(unused_variables)] on by default\nhelp: consider prefixing with an underscore: `_a`","range":{"end":{"character":6,"line":2},"start":{"character":5,"line":2}},"severity":2,"source":"rustc"}],"uri":"file:///C:/Users/llowrey/Documents/workspaces/personal/testo/src/main.rs"}}
[t=1567529326084] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"window/progress","params":{"done":null,"id":"progress_1","message":"testo cfg(test)","percentage":null,"title":"Building"}}
[t=1567529326361] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"window/progress","params":{"done":true,"id":"progress_1","message":null,"percentage":null,"title":"Building"}}
[t=1567529326364] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"window/progress","params":{"done":null,"id":"progress_0","message":null,"percentage":null,"title":"Indexing"}}
[t=1567529326366] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"","message":"invalid suffix `x` for integer literal\n\ninvalid suffix `x`\n\nhelp: the suffix must be one of the integral types (`u32`, `isize`, etc)","range":{"end":{"character":11,"line":2},"start":{"character":9,"line":2}},"severity":1,"source":"rustc"}],"uri":"file:///C:/Users/llowrey/Documents/workspaces/personal/testo/src/main.rs"}}
[t=1567530729955] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 214
```
I get this in .log a lot when working with rust files:
```
!ENTRY org.eclipse.lsp4e 4 0 2019-09-03 15:29:51.898
!MESSAGE The pipe is being closed
!STACK 0
java.io.IOException: The pipe is being closed
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:191)
	at org.eclipse.lsp4e.LoggingStreamConnectionProviderProxy.stop(LoggingStreamConnectionProviderProxy.java:210)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$5(LanguageServerWrapper.java:356)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$6(LanguageServerWrapper.java:363)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:1004)
	at java.base/java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2307)
	at org.eclipse.lsp4e.LanguageServerWrapper.stop(LanguageServerWrapper.java:362)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:184)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:576)
	at org.eclipse.lsp4e.DocumentContentSynchronizer.documentChanged(DocumentContentSynchronizer.java:89)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged2(AbstractDocument.java:747)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:716)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:700)
	at org.eclipse.jface.text.AbstractDocument.fireDocumentChanged(AbstractDocument.java:774)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1105)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.replace(SynchronizableDocument.java:176)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1123)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.replace(SynchronizableDocument.java:164)
	at org.eclipse.jface.text.DefaultDocumentAdapter.replaceTextRange(DefaultDocumentAdapter.java:236)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7426)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8303)
	at org.eclipse.swt.custom.StyledText.doBackspace(StyledText.java:2308)
	at org.eclipse.swt.custom.StyledText.invokeAction(StyledText.java:7215)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6071)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6098)
	at org.eclipse.swt.custom.StyledText.lambda$1(StyledText.java:5787)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1080)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1107)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1490)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4877)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:353)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4759)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3545)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	Suppressed: java.io.IOException: The pipe is being closed
		at java.base/java.io.FileOutputStream.writeBytes(Native Method)
		at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
		at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
		at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
		at java.base/java.io.FilterOutputStream.flush(FilterOutputStream.java:153)
		at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
		... 62 more

!ENTRY org.eclipse.corrosion 1 0 2019-09-03 15:29:52.070
!MESSAGE RLS settings for Corrosion path not found at C:\Users\llowrey/.cargo/rls.conf.

!ENTRY org.eclipse.corrosion 1 0 2019-09-03 15:29:52.288
!MESSAGE RLS settings for Corrosion path not found at C:\Users\llowrey/.cargo/rls.conf.
```

Also from .log:
```
!ENTRY org.eclipse.lsp4e 4 0 2019-09-03 15:14:23.017
!MESSAGE 
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.eclipse.lsp4e.operations.hover.LSBasedHover.getHoverRegion(LSBasedHover.java:187)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverRegion(CompositeTextHover.java:101)
	at org.eclipse.jface.text.TextViewerHoverManager.computeInformation(TextViewerHoverManager.java:142)
	at org.eclipse.jface.text.AbstractInformationControlManager.doShowInformation(AbstractInformationControlManager.java:1101)
	at org.eclipse.jface.text.AbstractHoverInformationControlManager$MouseTracker.mouseHover(AbstractHoverInformationControlManager.java:511)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:212)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)

!ENTRY org.eclipse.lsp4e 4 0 2019-09-03 15:14:23.523
!MESSAGE 
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.eclipse.lsp4e.operations.hover.LSBasedHover.getHoverInfo(LSBasedHover.java:108)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:60)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:169)

!ENTRY org.eclipse.lsp4e 4 0 2019-09-03 15:14:25.206
!MESSAGE 
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.eclipse.lsp4e.operations.hover.LSBasedHover.getHoverRegion(LSBasedHover.java:187)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverRegion(CompositeTextHover.java:101)
	at org.eclipse.jface.text.TextViewerHoverManager.computeInformation(TextViewerHoverManager.java:142)
	at org.eclipse.jface.text.AbstractInformationControlManager.doShowInformation(AbstractInformationControlManager.java:1101)
	at org.eclipse.jface.text.AbstractHoverInformationControlManager$MouseTracker.mouseHover(AbstractHoverInformationControlManager.java:511)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:212)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)

!ENTRY org.eclipse.lsp4e 4 0 2019-09-03 15:14:25.710
!MESSAGE 
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.eclipse.lsp4e.operations.hover.LSBasedHover.getHoverInfo(LSBasedHover.java:108)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:60)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:169)
```

**Comment by norru** [comment]
`Rust edition in Eclipse IDE	0.4.1.201903251734` looks a very old version.

**Comment by akurtakov** [comment]
Closing as per last comment from 3 years ago. If you still face the issue with latest version please reopen
