### ISSUE TITLE
Debugging not possible with rust 1.51 because "launchConfigEnv" is null 

### ISSUE THREAD

**Issue by 3ueb** [eclipse/corrosion#372]
I believe this a corrision Problem in short I have the same problem that this guy has
https://stackoverflow.com/questions/66258636/debugging-rust-on-eclipse-corrosion-no-longer-works-on-fresh-install

I installed eclipseide-rust-1.2.0-linux.gtk.x86_64.tar.gz.

I use Ubuntu 20.04 and with the package from ubuntu it worked. I don't know the version of rust i believe it was 1.47.
I remove the default ubuntu rust package and install rust 1.51 and know I can't debug the code.
Here is the error Log
`java.lang.NullPointerException: Cannot read the array length because "launchConfigEnv" is null
	at org.eclipse.corrosion.debug.RustGDBLaunchWrapper.getLaunchEnvironment(RustGDBLaunchWrapper.java:44)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunch.getGDBVersion(GdbLaunch.java:509)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launchDebugSession(GdbLaunchDelegate.java:156)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launchDebugger(GdbLaunchDelegate.java:108)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launch(GdbLaunchDelegate.java:96)
	at org.eclipse.corrosion.debug.RustDebugDelegate.launch(RustDebugDelegate.java:110)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:807)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:718)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`

**Comment by mickaelistria** [comment]
Can you please details the steps to reproduce this issue from a new project?

**Comment by 3ueb** [comment]
I did nothing special. I install the eclipseide-rust-1.2.0-linux.gtk.x86_64.tar.gz. package. I installed rust with 
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh^C`.

Then I create  a default Hello World projct in the IDE and debugging works. But I have the same Error describe here https://github.com/eclipse/corrosion/issues/369. In the internet I found that the reason could be, that I installed rust two time. Indeed I installed rust with the Ubuntu package system. I remove the Ubuntu package. Next corrosion didn't find rust-gdb any more. 
I setup in the "Debug Configuration... --> Debugger --> GDB debugger" to /home/u/.cargo/bin/rust-gdb.
After that I get the Error Message when I try to Debug the code.

**Comment by 3ueb** [comment]
Compiling and Running works but I can't debug the code anymore.

**Comment by 3ueb** [comment]
Building the Plugin by my selves works and Intall the Plugin with eclipse 3.19 works. I believe the  eclipseide-rust-1.2.0-linux.gtk.x86_64.tar.gz package is broken and has to be updated.

**Comment by mickaelistria** [comment]
I just tried the same package (fresh install), on Linux, with Rust 1.50
* File > New > Rust > Cargo Project > Finish
* In `main.rs` put a breakpoint on `print(...)` (line 2)
* Right-click > Debug As > Rust
=> Got breakpoint hit
