### ISSUE TITLE
Error while starting debugger

### ISSUE THREAD

**Issue by dc740** [eclipse/corrosion#64]
This error appears in the workspace logs when I try to debug a simple main function:
```
!ENTRY org.eclipse.core.jobs 4 2 2018-05-15 01:14:08.044
!MESSAGE An internal error occurred during: "Launching New_configuration".
!STACK 0
org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:73)
	at org.eclipse.core.runtime.Path.initialize(Path.java:641)
	at org.eclipse.core.runtime.Path.<init>(Path.java:238)
	at org.eclipse.core.runtime.Path.<init>(Path.java:186)
	at org.eclipse.core.runtime.Path.fromOSString(Path.java:92)
	at org.eclipse.corrosion.RustGDBLaunchWrapper.getGDBLocation(RustGDBLaunchWrapper.java:75)
	at org.eclipse.corrosion.RustGDBLaunchWrapper.getLaunchEnvironment(RustGDBLaunchWrapper.java:56)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunch.getGDBVersion(GdbLaunch.java:524)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launchDebugSession(GdbLaunchDelegate.java:142)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launchDebugger(GdbLaunchDelegate.java:101)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launch(GdbLaunchDelegate.java:90)
	at org.eclipse.corrosion.debug.RustDebugDelegate.launch(RustDebugDelegate.java:95)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

Steps to reproduce:
Create a new cargo project from the eclipse UI
Set a breakpoing in the only available line     println!("Hello, world!");
Create a new debug configuration for target "run".
It gives that error as result

**Comment by mickaelistria** [comment]
The issue here might be that `gdb` is not available in your PATH. Can you check?
But I believe it's a suboptimal construct in the code. Since we already have information about GDB in the launch configuration, those should be reused instead of recomputing the location of GDB. cc @LucasBullen

**Comment by mickaelistria** [comment]
@akurtakov Do you think you could have a look at how to replace RustGDBLaunchWrapper#getGDBLocation implementation by something that relies on CDT/GDB integration code?

**Comment by akurtakov** [comment]
@dc740 is gdb on your path? Which operating system and version is this?

**Comment by akurtakov** [comment]
@dc740 Assuming you're on windows can you try the referenced patch?

**Comment by dc740** [comment]
I'm on Linux. I didn't have gdb installed, but I mistakenly assumed it would work because I saw the rust-gdb command line available in my box. I think this ticket can be safely closed and consider it a PEBKAC

I now see that even rust-gdb asks for gdb when run. (it was my first time debugging on this PC, and using this plugin, I assumed gdb was installed)

As an improvement, could I ask for a dialog informing the user that gdb was not found? Thank you
